Log plot multi user
Agora-wireless/Agora pull request #362
Opened 2022-07-01 04:09 UTC by di-mu

2022-07-19 20:04 UTC, rdoosty commented on src/client/ue_worker.cc
> +      const std::string fname_ext = std::to_string(frame_id) + "_" +
For smaller intervals, this will generate too many files. Perhaps we should record in a subdirectory.

2022-07-19 20:46 UTC, di-mu commented on src/client/phy-ue.cc
> +                const arma::uvec csi_rec_sc({20, 140, 280});
Tried but can't use constexpr. arma objects are not literal.

2022-07-22 22:32 UTC, asedlmayr requested changes
Prioritize the memory leaks and we will get this pushed in.

2022-07-22 22:32 UTC, asedlmayr commented on src/common/loggers/csv_logger.h
> +constexpr size_t kCsvIdStart = 0;
Would be better to make these some sort of enumerated type

2022-07-22 22:32 UTC, asedlmayr commented on src/common/loggers/csv_logger.h
> +#include <vector>
Not sure why this is necessary?  You have no vectors in the header.

2022-07-22 22:32 UTC, asedlmayr commented on src/common/loggers/csv_logger.h
> +#include "symbols.h"
What is the symbols dependency?

2022-07-22 22:32 UTC, asedlmayr commented on src/common/loggers/csv_logger.cc
> +    std::string filename =
What is the remove doing?  add a comment

2022-07-22 22:32 UTC, asedlmayr commented on src/common/loggers/mat_logger.h
>  constexpr size_t kBSAnts = 8;
These look suspecious..... Why are these fixed values, should you be using the configurations?

2022-07-22 22:32 UTC, asedlmayr commented on src/client/phy-ue.cc
> +#include <sys/stat.h>
Lets not create directories in phy-ue class

2022-07-22 22:32 UTC, asedlmayr commented on src/client/phy-ue.cc
> +  mkdir("log", 0777);
Lets not create directories in phy-ue class

2022-07-22 22:32 UTC, asedlmayr commented on src/client/phy-ue.cc
> +                constexpr std::array<size_t, kRecScNum> csi_rec_sc = {20, 140,
All values like 20,140, 200 should have names.  it is not obvious why you picked these values.

2022-07-22 22:32 UTC, asedlmayr commented on src/client/phy-ue.cc
> +                constexpr size_t kRecScNum = 3;
constexpr should not embedded in a function. Move to the top.

2022-07-22 22:32 UTC, asedlmayr commented on src/client/phy-ue.cc
>                if (kEnableCsvLog) {
You removed all but 1 other kEnableCsvLog in phy ue.  Probably best to remove this one too.   You can just pass these into phy_stats and let it make the decision.

2022-07-22 22:32 UTC, asedlmayr commented on src/client/phy-ue.cc
> +              if (kEnableCsvLog) {
Remove this too.  Just let RecordBer and RecordSer (maybe make 1 function) do nothing if logging is disabled

2022-07-26 22:24 UTC, di-mu commented on src/common/phy_stats.cc
> +void PhyStats::UpdateUlPilotSnr(size_t frame_id, size_t ue_id, size_t ant_id,
arma can't construct mat from const pointer.

2022-07-30 00:58 UTC, merged